### ISSUE TITLE
Transitions based on total time?

### ISSUE THREAD

**Issue by kalexmills** [joelschutz/stagehand#1]
Would it be possible / desirable to implement transitions based on wallclock time instead of ticks? I find this more intuitive to use when designing.

For instance; fade would take a `time.Duration` for the total fade time.

**Comment by joelschutz** [comment]
I guess you can implement something like:
```go
currentProgress := float64(time.Now().Sub(initialTime)) / float64(desiredDuration)
```
That would give you a value between 0 and 1 that you can use as the transition progress.

**Comment by joelschutz** [comment]
> ```go
> currentProgress := float64(time.Now().Sub(initialTime)) / float64(desiredDuration)
> ```

After thinking about the problem I figured that this solution can bit a bit ~~unstable~~ unpredictable on very laggy games. A more stable method would be to pre-calculate factor per frame, it would need a formula to find that value.

I'm moving right now and can't look at thi at the moment, but i'm creating a branch to refactor this part.

**Comment by kalexmills** [comment]
> After thinking about the problem I figured that this solution can bit a bit unstable on very laggy games.

I basically use the solution you proposed in my own games and they seem to work. What sort of instability are you concerned about?

**Comment by joelschutz** [comment]
> > After thinking about the problem I figured that this solution can bit a bit unstable on very laggy games.
> 
> I basically use the solution you proposed in my own games and they seem to work. What sort of instability are you concerned about?

Sorry, I mean to write unpredictable. The animation can jump in non uniform ways.
